spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/billiards_hall_reservation_system
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd                 # 日期格式
    time-zone: GMT+8                        # 设置时区
    default-property-inclusion: non_null    # 不返回空字段

mybatis-plus:
  global-config:
    db-config:
      id-type: auto       #全局id生成策略：自增
  mapper-locations: classpath*:/mapper/**/*.xml


server:
  port: 8080

  # DataSource Config
  spring:
    datasource:
      driver-class-name: org.h2.Driver
      schema: classpath:db/schema-h2.sql
      username: root
      password: test
    sql:
      init:
        schema-locations: classpath:db/schema-h2.sql
        data-locations: classpath:db/data-h2.sql